{{- $appname := .Values.global.name -}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ $appname }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ $appname | quote }}
spec:
  type: ClusterIP
  selector:
    app: {{ $appname | quote }}
  publishNotReadyAddresses: false
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
  - name: metrics
    port: 9114

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.deployment.serviceName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ $appname | quote }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: {{ $appname | quote }}
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  - name: metrics
    port: 9114
