{{- $appname := .Values.global.name -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $appname }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ $appname | quote }}
spec:
  serviceName: {{ .Values.deployment.serviceName }}
  selector:
    matchLabels:
      app: {{ $appname | quote }}
  replicas: 3
  volumeClaimTemplates:
  - metadata:
      name: {{ $appname }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.deployment.volumeClaimTemplates.storage }}
      storageClassName: {{ .Values.deployment.volumeClaimTemplates.storageClassName }}
  template:
    metadata:
      labels:
        app: {{ $appname | quote }}
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.deployment.containers.images }}
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        resources:
          requests:
            cpu: {{ .Values.deployment.containers.resources.requests.cpu | quote }}
            memory: {{ .Values.deployment.containers.resources.requests.memory }}
          limits:
            cpu: {{ .Values.deployment.containers.resources.limits.cpu | quote }}
            memory: {{ .Values.deployment.containers.resources.limits.memory }}
        env:
          - name: cluster.name
            value: {{ $appname | quote }}
          - name: discovery.seed_hosts
            value: {{ .Values.deployment.serviceName | quote }}
          - name: cluster.initial_master_nodes
            value: {{ .Values.deployment.clusterNodes }}
          - name: ES_JAVA_OPTS
            value: "-Xmx1g -Xms1g"
        volumeMounts:
          - name: {{ $appname | quote }}
            mountPath: /usr/share/elasticsearch/data
